### ISSUE TITLE
Show application error

### ISSUE THREAD

**Issue by Giancarlo-Ma** [andrewmatveychuk/azure.ghost-web-app-for-containers#1]
The deployment is successful, but I can not visit the wesite

**Comment by andrewmatveychuk** [comment]
@Giancarlo-Ma, how long have you waited for the site to start? It might take a few minutes on the first run to download the container images and perform all MySQL and Ghost initialization tasks.

**Comment by Giancarlo-Ma** [comment]
> @Giancarlo-Ma, how long have you waited for the site to start? It might take a few minutes on the first run to download the container images and perform all MySQL and Ghost initialization tasks.

The error shows that database can not be connected, the following are some logs:

`ER_HOST_NOT_PRIVILEGED: Host '172.16.3.3' is not allowed to connect to this MySQL server`

**Comment by andrewmatveychuk** [comment]
I know it might sound weird but give the containers some time to finish the initialization process. [On the first run, a MySQL container performs the default database initialization and refuses connections](https://hub.docker.com/_/mysql). Consequentially, the Ghost container will fail to start until the database server is ready to accept connections.
As I mentioned earlier, depending on your app service plan, it might take a while for all the initialization to finish and containers to start in the correct order. The subsequent container restarts take far less time. For example, in my deployment to the B1 service plan, I had to wait for about 5 minutes until the containers are restarted few times because of errors by the app service.
